name: pulseboard_analytics_example
description: Example app demonstrating the Pulseboard Flutter SDK.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pulseboard_analytics:
    path: ../
